### PR TITLE
revise encoder to properly handle strings, encoding values, etc

### LINKED ISSUE #1: No quotes around strings
Hey. I am passing options from my NodeJS environment to my Sass stuff, only to find out that my E-Mail address breaks things. In other words, by checking back, it seems that no quotation is applied to the strings. Cam you fix that? Using the very code you linked for the JsonToSass() function returns the output with the strings being quoted.

### LINKED ISSUE #2: Add cacheable flag
Any reason why this loader is not cacheable? 
https://github.com/webpack/docs/wiki/how-to-write-a-loader#flag-itself-cacheable-if-possible

### PR DESCRIPTION
**Pull request by tracker1**
revise encoder to properly handle strings, encoding values, etc
Add default node .gitignore
## 

This should take care of string encoding issues...

fixes #1 
fixes #2

### CODE REVIEW

**Comment by tracker1** [comment]
Strings that aren't colors, or measurements are enclosed as quoted strings... may need to use `unquote()` if there's a need for combining with other values.... such as `url($root/unqoute($injectedPathVariable))`

**Comment by karlnp** [comment]
Doesn't seem to work with paths.. at least I can't get it to work with paths. Will have to fork and experiment.

**Comment by EdwardIrby** [comment]
I will review this this weekend and pull it in if all's good. On another note I'm probably going to drop this project after the holidays once I've solved the open issues. I've moved on from SCSS to postCC in my work at home and in the office these days.

**Comment by tracker1** [comment]
It worked for what I was trying to do.. I was having issues using some declarations that were coming through as strings.  I'm not using it either, currently.

**Comment by mbahoshy** [comment]
This would be great to get in the project. Currently trying to pass in img urls as string, and having to monkey-patch library to get it working

**Comment by brandoniffert** [comment]
Hey @EdwardIrby, any chance of getting this PR merged? I would like to use this in a project and this is the only hold up.

Thanks

**Comment by EdwardIrby** [comment]
This breaks the basic functionality of the this node module which is to allow a user to declare their vars in json or a js file as documented. The user can do simple declaration or create maps. I tested this in my simplest use case and it failed. If you need the features in this pull request I recommend using traker1's fork.

**Pull request closed without merging**
